package model.dataAccessLayer.entity;
// Generated Mar 18, 2018 10:53:52 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItiStoreYUser generated by hbm2java
 */
public class ItiStoreYUser implements java.io.Serializable {

    private Long recid;
    private String name;
    private String password;
    private String email;
    private String address;
    private String job;
    private Date birthdate;
    private float creditlimit;
    private Set itiStoreYInterests = new HashSet();
    private Set itiStoreYCarts = new HashSet(0);

    public ItiStoreYUser() {
    }

    public ItiStoreYUser(Long recid) {
        this.recid = recid;
    }

    public ItiStoreYUser(Long recid, String name, String password, String email, String address, String job, Date birthdate, float creditlimit, Set itiStoreYInterests, Set itiStoreYCarts) {
        this.recid = recid;
        this.name = name;
        this.password = password;
        this.email = email;
        this.address = address;
        this.job = job;
        this.birthdate = birthdate;
        this.creditlimit = creditlimit;
        this.itiStoreYInterests = itiStoreYInterests;
        this.itiStoreYCarts = itiStoreYCarts;
    }

    public Long getRecid() {
        return this.recid;
    }

    public void setRecid(Long recid) {
        this.recid = recid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public float getCreditlimit() {
        return this.creditlimit;
    }

    public void setCreditlimit(float creditlimit) {
        this.creditlimit = creditlimit;
    }

    public Set getItiStoreYInterests() {
        return this.itiStoreYInterests;
    }

    public void setItiStoreYInterests(Set itiStoreYInterests) {
        this.itiStoreYInterests = itiStoreYInterests;
    }

    public Set getItiStoreYCarts() {
        return this.itiStoreYCarts;
    }

    public void setItiStoreYCarts(Set itiStoreYCarts) {
        this.itiStoreYCarts = itiStoreYCarts;
    }
}
