package model.dataAccessLayer.entity;
// Generated Mar 18, 2018 10:53:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * ItiStoreYProductcart generated by hbm2java
 */
public class ItiStoreYProductcart implements java.io.Serializable {

    private Long recid;
    private ItiStoreYCart itiStoreYCart;
    private ItiStoreYProduct itiStoreYProduct;
    private BigDecimal numofitems;

    public ItiStoreYProductcart() {
    }

    public ItiStoreYProductcart(Long recid) {
        this.recid = recid;
    }

    public ItiStoreYProductcart(Long recid, ItiStoreYCart itiStoreYCart, ItiStoreYProduct itiStoreYProduct, BigDecimal numofitems) {
        this.recid = recid;
        this.itiStoreYCart = itiStoreYCart;
        this.itiStoreYProduct = itiStoreYProduct;
        this.numofitems = numofitems;
    }

    public Long getRecid() {
        return this.recid;
    }

    public void setRecid(Long recid) {
        this.recid = recid;
    }

    public ItiStoreYCart getItiStoreYCart() {
        return this.itiStoreYCart;
    }

    public void setItiStoreYCart(ItiStoreYCart itiStoreYCart) {
        this.itiStoreYCart = itiStoreYCart;
    }

    public ItiStoreYProduct getItiStoreYProduct() {
        return this.itiStoreYProduct;
    }

    public void setItiStoreYProduct(ItiStoreYProduct itiStoreYProduct) {
        this.itiStoreYProduct = itiStoreYProduct;
    }

    public BigDecimal getNumofitems() {
        return this.numofitems;
    }

    public void setNumofitems(BigDecimal numofitems) {
        this.numofitems = numofitems;
    }

}
